name: Deploy to Self-Hosted Server

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        
      - name: Deploy to Web Directory
        run: |
          rsync -avz --delete \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='.env' \
          --exclude='/storage' \
          --exclude='/node_modules' \
          --exclude='/public/storage' \
          --exclude='/public/build' \
          ./ /var/www/habit/
          
      - name: Install NPM & Build
        run: |
          cd /var/www/habit
          npm install
          npm run build

      - name: Optimizations & Migrations
        run: |
          cd /var/www/habit
          php artisan migrate --force
          php artisan optimize:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link
